# roles/consul/tasks/main.yml
- name: upgrade all packages
  yum: name=* state=latest

- name: install unzip
  yum:
    name: "unzip"
    state: present

- name: install jq
  become_user: root
  yum:
    name: "jq"
    state: present

- name: install wget
  yum:
    name: "wget"
    state: present

- name: pip install python dependencies
  pip:
    name:
      - "boto3"
      - "botocore"
      - "kazoo"
      - "paramiko"
    state: present

- name: move the consul installation script to the /tmp dir
  copy:
    src: ../files/install-consul
    dest: /tmp
    mode: u=rwx,g=rx,o=rx

- name: move the consul installation script to the /tmp dir
  copy:
    src: ../files/run-consul
    dest: /tmp
    mode: u=rwx,g=rx,o=rx

- name: install consul using the copied bash and python scripts
  shell: /tmp/install-consul/install-consul --version {{ consul_version }} --user ec2-user