- name: Check if AMI with the same name exists
  ec2_ami_facts:
    region: "{{ region_id }}"
    filters:
      "tag:Name": "{{ ami_name }}"
  register: ami_find


- name: Deregister AMI if it exists
  block:
    - ec2_ami:
        image_id: "{{ ami_find.images[0].image_id}}"
        state: absent
      when: ami_find.images[0].state == 'available'
  when: ami_find.images[0] is defined

- name: Creating the AMI from of the instance
  ec2_ami:
    instance_id: "{{ base_instance_id }}"
    wait: yes
    name: "{{ ami_name }}"
    tags:
      Name: "{{ ami_name }}"
  register: image

- name: Terminate base instance
  ec2:
    instance_ids: "{{ base_instance_id }}"
    region: "{{ region_id }}"
    state: absent
    wait: True
    vpc_subnet_id: "{{ vpc_subnet_id }}"