- name: upgrade all packages
  yum: name=* state=latest

- name: Check for reboot hint.
  shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint

- name: Rebooting ...
  command: shutdown -r now "Reboot required for updated kernel"
  async: 0
  poll: 0
  sudo: true
  ignore_errors: true
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting

- name: Wait for thing to reboot...
  pause: seconds=90
  when: rebooting is changed

- name: install packages
  yum:
    name:
     - "unzip"
     - "wget"
     - "ca-certificates"
     - "zip"
     - "net-tools"
     - "tar"
     - "nmap-ncat"
   #  - "apt-transport-https"
     - "ca-certificates "
     - "curl"
     - "docker"
   #  - "software-properties-common"
    state: present

- name: pip install python dependencies
  pip:
    name:
      - "boto3"
      - "botocore"
      - "kazoo"
      - "paramiko"
      - "docker-compose"
    state: present

- name: give permissions to execute docker
  shell: usermod -aG docker $(whoami)
