plugin: aws_ec2
regions:
  - eu-west-1
  - eu-west-2
hostnames:
  #- tag:Name=Tag1,Name=Tag2  # return specific hosts only
  #- tag:CustomDNSName
  - dns-name
  - private-ip-address
keyed_groups:
  # add e.g. x86_64 hosts to an arch_x86_64 group
  - prefix: arch
    key: 'architecture'
  # add hosts to e.g. instance_type_z3_tiny
  - prefix: instance_type
    key: instance_type
  # create security_groups_sg_abcd1234 group for each SG
  - key: 'security_groups|json_query("[].group_id")'
    prefix: 'security_groups'
  # create a group for each value of the Application tag
  - key: tags.Application
    separator: ''
  # create a group for each value of the Name tag
  - key: tags.Name
    separator: ''
  # create a group per region e.g. aws_region_us_east_2
  - key: placement.region
    prefix: aws_region
compose:
  # set the ansible_host variable to connect with the private IP address without changing the hostname
  ansible_host: public_ip_address
