- hosts: localhost
  remote_user: root
  vars_files:
    - vars/consul_vars.yml
    - variables.yml
  tasks:
    - name: copy account to ../Terraform/modules/consul_ASG/variables.tf
      lineinfile:
        dest: ../Terraform/modules/consul_ASG/variables.tf
        line: "variable \"account\" { default = \"{{ aws_account_id }}\" description = \"AWS account ID\" }"
        state: present
    - name: insert AWS access key into run_consul script
      replace:
        path: ./roles/consul/files/run-consul/run-consul
        regexp: '(\<Access key for user allowed to assume role defined in Terraform\>)'
        replace: '{{ aws_access_key }}'
    - name: insert AWS secret key into run_consul script
      replace:
        path: ./roles/consul/files/run-consul/run-consul
        regexp: '(\<Secret key for user allowed to assume role defined in Terraform\>)'
        replace: '{{ aws_secret_key }}'
    - name: insert .pem file into ./roles/consul/files/install-consul/conf_consul.py
      replace:
        path: ./roles/consul/files/install-consul/conf_consul.py
        regexp: '(\<your .pem file\>)'
        replace: '{{ pem_file }}'
    - name: move the .pem file ./roles/consul/files/install-consul dir
      copy:
        src: '{{ pem_file_location }}/{{ pem_file }}'
        dest: ./roles/consul/files/install-consul
        mode: u=r,g=r,o=r
    - name: Run common/tasks/main.yaml
      import_role:
        name: common
    - meta: refresh_inventory

- hosts: Console_Node
  become: yes
  remote_user: ec2-user
  vars_files:
    - vars/consul_vars.yml
    - variables.yml
  roles:
    - role: consul

- hosts: localhost
  remote_user: root
  vars_files:
    - vars/consul_vars.yml
  tasks:
    - name: Run common/tasks/create_ami.yaml instead of 'main'
      import_role:
        name: common
        tasks_from: create_ami