- hosts: localhost
  remote_user: root
  vars_files:
    - vars/kafka_connect_vars.yml
    - variables.yml
  tasks:
    - name: copy account to ../Terraform/envs/modules/kafka_connect_ASG/variables.tf
      lineinfile:
        dest: ../Terraform/modules/kafka_connect_ASG/variables.tf
        line: "variable \"account\" { default = \"{{ aws_account_id }}\" description = \"AWS account ID\" }"
        state: present
    - name: insert .pem file into ./roles/kafka_connect/files/install-kafka_connect/conf_kafka_connect.py
      replace:
        path: ./roles/kafka_connect/files/install-kafka_connect/conf_kafka_connect.py
        regexp: '(\<your .pem file\>)'
        replace: '{{ pem_file }}'
    - name: move the .pem file ./roles/kafka_connect/files/install-kafka_connect
      copy:
        src: '{{ pem_file_location }}/{{ pem_file }}'
        dest: ./roles/kafka_connect/files/install-kafka_connect
        mode: u=r,g=r,o=r
    - name: Run common/tasks/main.yaml
      import_role:
        name: common
    - meta: refresh_inventory

- hosts: Kafka_Connect_Node
  become: yes
  remote_user: ec2-user
  vars_files:
    - vars/kafka_connect_vars.yml
  roles:
    - role: kafka_connect

- hosts: localhost
  remote_user: root
  vars_files:
    - vars/kafka_connect_vars.yml
  tasks:
    - name: Run common/tasks/create_ami.yaml instead of 'main'
      import_role:
        name: common
        tasks_from: create_ami