- hosts: localhost
  remote_user: root
  vars_files:
    - vars/management_tools_vars.yml
    - variables.yml
  tasks:
    - name: copy account to ../Terraform/modules/management_ASG/variables.tf
      lineinfile:
        dest: ../Terraform/modules/management_ASG/variables.tf
        line: "variable \"account\" { default = \"{{ aws_account_id }}\" description = \"AWS account ID\" }"
        state: present
    - name: insert .pem file into ./roles/management_tools/files/install-tools/conf_tools.py
      replace:
        path: ./roles/management_tools/files/install-tools/conf_tools.py
        regexp: '(\<your .pem file\>)'
        replace: '{{ pem_file }}'
    - name: move the .pem file ./roles/management_tools/files/install-tools dir
      copy:
        src: '{{ pem_file_location }}/{{ pem_file }}'
        dest: ./roles/management_tools/files/install-tools
        mode: u=r,g=r,o=r
    - name: Run common/tasks/main.yaml
      import_role:
        name: common
    - meta: refresh_inventory

- hosts: Management_Tools_Node
  become: yes
  remote_user: ec2-user
  vars_files:
    - vars/management_tools_vars.yml
    - variables.yml
  roles:
    - role: management_tools

- hosts: localhost
  remote_user: root
  vars_files:
    - vars/management_tools_vars.yml
  tasks:
    - name: Run common/tasks/create_ami.yaml instead of 'main'
      import_role:
        name: common
        tasks_from: create_ami