- hosts: localhost
  remote_user: root
  vars_files:
    - vars/management_tools_vars.yml
    - variables.yml
  tasks:
    - name: Run common/tasks/main.yaml
      import_role:
        name: common
    - meta: refresh_inventory

- hosts: Management_Tools_Node
  become: yes
  remote_user: ec2-user
  vars_files:
    - vars/management_tools_vars.yml
  roles:
    - role: management_tools

- hosts: localhost
  remote_user: root
  vars_files:
    - vars/management_tools_vars.yml
  tasks:
    - name: Run common/tasks/create_ami.yaml instead of 'main'
      import_role:
        name: common
        tasks_from: create_ami